### PR TITLE
Remove placeholder dbxrefs in `omp-edit.obo`

### PR DESCRIPTION
**Pull request by althonos**
Hi there!
I'm working with @cmungall on improving the syntax and semantics of the OBO format. This PR removes some placeholder xrefs in `omp-edit.obo` that end up polluting the release file. Other than that, OMP should be compliant with the version 1.4 of the OBO format!

### CODE REVIEW

**Comment by dsiegele** [comment]
Thanks, Martin.

**Comment by althonos** [comment]
Would you mind making a new release of `omp.obo` ? This way I could add it back to the OBO Foundry test suite.

**Comment by nsuvarnaiari** [comment]
Hi @althonos 

I will be making a release today. Will update the ticket as soon as I am done.

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Hi @althonos

Release is done. 

Thanks,
Suvvi

**Pull request merged**
